url: https://xplorezest.com/
baseurl: 

# Site settings
title: XploreZest
email: xplorezest@gmail.com
description: "Break through the burnout and live with unshakeable enthusiasm. Your most vibrant self is waiting to be found."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/xiaowenzhang/

# Build settings
markdown: kramdown
permalink: pretty